# Generated by Django 5.2.4 on 2025-08-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casa',
            new_name='Casas',
        ),
        migrations.AlterModelOptions(
            name='casas',
            options={'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterModelOptions(
            name='opiniones',
            options={'verbose_name': 'Opinión', 'verbose_name_plural': 'Opiniones'},
        ),
    ]
