# Generated by Django 5.2.4 on 2025-08-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_casa_casas_alter_casas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opiniones',
            name='calificacion',
        ),
    ]
