# Generated by Django 5.2.4 on 2025-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_remove_opiniones_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casas',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
