# Generated by Django 5.2.4 on 2025-08-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_casas_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='casas',
            name='descripcion_promocion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la promoción'),
        ),
        migrations.AddField(
            model_name='casas',
            name='en_promocion',
            field=models.BooleanField(default=False, verbose_name='En promoción'),
        ),
        migrations.AddField(
            model_name='casas',
            name='fecha_fin_promocion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin promoción'),
        ),
        migrations.AddField(
            model_name='casas',
            name='precio_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio promocional'),
        ),
    ]
