# Generated by Django 5.2.4 on 2025-08-24 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_contacto_remove_casas_descripcion_promocion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='opiniones/'),
        ),
        migrations.AddField(
            model_name='opiniones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
