# Generated by Django 5.2.4 on 2025-08-25 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_opiniones_imagen_opiniones_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opiniones',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Opinión', 'verbose_name_plural': 'Opiniones'},
        ),
        migrations.RemoveField(
            model_name='opiniones',
            name='usuario',
        ),
        migrations.AddField(
            model_name='opiniones',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opiniones',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opiniones',
            name='user_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='opiniones/', verbose_name='Imagen'),
        ),
    ]
