# Generated by Django 5.2.4 on 2025-08-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_opiniones_options_remove_opiniones_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opiniones',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='opiniones',
            name='user_token',
        ),
        migrations.AddField(
            model_name='opiniones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
