# Generated by Django 5.2.4 on 2025-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_remove_opiniones_nombre_remove_opiniones_user_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casas',
            name='clave',
            field=models.IntegerField(verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='destacada',
            field=models.BooleanField(default=False, verbose_name='Casa Destacada'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='numhabitaciones',
            field=models.IntegerField(verbose_name='Número de habitaciones'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='servicios',
            field=models.TextField(verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='comentario',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
